version: "2"
services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command:
      - bash 
      - runDevServer.sh 
    ports:
      - 3000:3000
      - 9102:9102
    environment:
      PUM_CONFIG_PATH: /stage/metricConfigs
    volumes:
      - ./serverSrc:/stage/serverSrc
      - ./clientSrc:/stage/clientSrc
      - ./config/metricConfigs:/stage/metricConfigs

  # prod-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #     # Note: in production you should not expose port 9102. It is exposed here just to make it easier to manually verify GET :9102/metrics
  #     - 9102:9102
  #   environment:
  #     PUM_CONFIG_PATH: /stage/metricConfigs
  #   volumes:
  #     - ./config/metricConfigs:/stage/metricConfigs

  demo-prom:
    image: prom/prometheus
    command:
      - -config.file=/prometheusConfig/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./demo/prometheusConfig:/prometheusConfig
    links:
      - dev-server:metrics-aggregator-dev-server

  demo-grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./demo/grafanaConfig:/grafana-data
    links:
      - demo-prom
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PATHS_DATA: /grafana-data

  # This server actually serves the demo code
  sample-web-server:
    image: nginx
    ports: 
      - 8080:80
    volumes:
      - ./demo/sampleApp:/usr/share/nginx/html:ro